
using Pkg
Pkg.activate(@__DIR__)
Pkg.add("Plots")
Pkg.add("StatsPlots")
Pkg.add("DataFrames")
Pkg.add("Random")
Pkg.add("CSV")
Pkg.add("MLJ")
Pkg.add("MLJLinearModels")
Pkg.add("NearestNeighborModels")
Pkg.add("CategoricalDistributions")
Pkg.add("CategoricalArrays")
Pkg.add("MLJLIBSVMInterface")
Pkg.add("LIBSVM")
Pkg.add("MLJDecisionTreeInterface")
Pkg.add("MLJFlux")
Pkg.add("Flux")
Pkg.add("MLJMultivariateStatsInterface")
Pkg.add("GLMNet")
